import { Member } from "@/components/tables/project-table/columns";

// utils/mockData.ts
export type Project = {
  id: number;
  title: string;
  description: string;
  testcaseCount: number;
  progress: number;
  startDate: string;
  deadline: string;
  status: "active" | "inactive" | "completed";
  priority: "high" | "medium" | "low";
  createdBy: string;
  members?: Member[]; // Make this optional
};

export function getDummyProjects(): Project[] {
  return [
    {
      id: 1,
      title: "Website Redesign",
      description: "Complete overhaul of company website with new UI/UX",
      testcaseCount: 42,
      progress: 75,
      startDate: "2023-06-01",
      deadline: "2023-12-15",
      status: "active",
      priority: "high",
      createdBy: "Alex Johnson",
      members: [],
    },
    {
      id: 2,
      title: "Mobile App Testing",
      description: "Comprehensive testing for new mobile banking application",
      testcaseCount: 68,
      progress: 30,
      startDate: "2023-08-10",
      deadline: "2024-02-28",
      status: "active",
      priority: "medium",
      createdBy: "Sarah Williams",
      members: [],
    },
    {
      id: 3,
      title: "API Security Audit",
      description: "Penetration testing for payment processing APIs",
      testcaseCount: 27,
      progress: 100,
      startDate: "2023-05-15",
      deadline: "2023-09-30",
      status: "active",
      priority: "high",
      createdBy: "Michael Chen",
      members: [],
    },
    {
      id: 4,
      title: "E-commerce Checkout",
      description: "Testing checkout flow for new e-commerce platform",
      testcaseCount: 35,
      progress: 50,
      startDate: "2023-09-01",
      deadline: "2024-01-20",
      status: "active",
      priority: "medium",
      createdBy: "Jessica Brown",
      members: [],
    },
    {
      id: 5,
      title: "Performance Optimization",
      description: "Load testing for high-traffic news portal",
      testcaseCount: 19,
      progress: 20,
      startDate: "2023-10-05",
      deadline: "2024-03-15",
      status: "active",
      priority: "low",
      createdBy: "David Miller",
      members: [],
    },
    {
      id: 6,
      title: "Accessibility Compliance",
      description: "WCAG 2.1 AA compliance testing for government portal",
      testcaseCount: 56,
      progress: 90,
      startDate: "2023-07-20",
      deadline: "2023-11-30",
      status: "active",
      priority: "high",
      createdBy: "Emily Davis",
      members: [],
    },
    {
      id: 7,
      title: "Legacy System Migration",
      description: "Testing data migration from legacy CRM to new platform",
      testcaseCount: 73,
      progress: 100,
      startDate: "2023-04-01",
      deadline: "2023-08-01",
      status: "completed",
      priority: "medium",
      createdBy: "Robert Wilson",
      members: [],
    },
    {
      id: 8,
      title: "IoT Device Testing",
      description: "Quality assurance for new smart home devices",
      testcaseCount: 48,
      progress: 40,
      startDate: "2023-09-15",
      deadline: "2024-05-01",
      status: "active",
      priority: "high",
      createdBy: "Jennifer Taylor",
      members: [],
    },
    {
      id: 9,
      title: "Chatbot Enhancement",
      description:
        "Improve natural language understanding for customer support chatbot",
      testcaseCount: 33,
      progress: 60,
      startDate: "2024-02-01",
      deadline: "2024-06-15",
      status: "active",
      priority: "medium",
      createdBy: "Nathaniel Gray",
      members: [],
    },
    {
      id: 10,
      title: "Cloud Cost Optimization",
      description: "Audit and reduce unnecessary cloud spending",
      testcaseCount: 25,
      progress: 45,
      startDate: "2024-04-05",
      deadline: "2024-08-30",
      status: "active",
      priority: "low",
      createdBy: "Linda White",
      members: [],
    },
    {
      id: 11,
      title: "Blockchain Integration",
      description: "Add blockchain-based transaction logging",
      testcaseCount: 64,
      progress: 10,
      startDate: "2024-10-01",
      deadline: "2025-03-31",
      status: "inactive",
      priority: "high",
      createdBy: "Carlos Rivera",
      members: [],
    },
    {
      id: 12,
      title: "AI Bug Detection",
      description: "Implement AI-based bug detection for QA automation",
      testcaseCount: 38,
      progress: 35,
      startDate: "2024-11-20",
      deadline: "2025-05-09",
      status: "active",
      priority: "high",
      createdBy: "Zoe King",
      members: [],
    },
    {
      id: 13,
      title: "Digital Twin Testing",
      description: "Validate digital twin simulations against physical models",
      testcaseCount: 29,
      progress: 5,
      startDate: "2025-01-10",
      deadline: "2025-07-20",
      status: "active",
      priority: "medium",
      createdBy: "Mason Lee",
      members: [],
    },
  ];
}
